group-provider.name=keycloak
keycloak.url=https://keycloak:8443
keycloak.client-id=trinodb
keycloak.client-secret=${ENV:OAUTH2_CLIENT_SECRET}
keycloak.realm=master
keycloak.keystore.path=/certs/trino-keystore.p12
keycloak.keystore.key=changeit
keycloak.trust-store-path=/certs/trino-keystore.p12
keycloak.trust-store-password=changeit