connector.name=hive
hive.metastore=file
hive.metastore.catalog.dir=file:///hive
hive.non-managed-table-writes-enabled=true
fs.native-local.enabled=true
local.location=/tmp/trino-metastore
hive.security=file
security.config-file=/etc/trino/catalog/hive-rules.json
security.refresh-period=1s